package br.ufrn.imd.projeto.GUI;

import javax.swing.SwingConstants;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Color;

/*
 * A interface gráfica do projeto
 */
/**
 *
 * @author Patricia & Fagner
 */
public class ProjetoGUI extends javax.swing.JFrame {

    /**
     * Creates new form ProjetoGUI
     */
    public ProjetoGUI() {
        initComponents();

        handler = new ProjetoGUIHandler();

        quadroBusca.setHorizontalAlignment(SwingConstants.LEFT);
        quadroBusca.setVerticalAlignment(SwingConstants.TOP);
        quadroSegmentar.setHorizontalAlignment(SwingConstants.LEFT);
        quadroSegmentar.setVerticalAlignment(SwingConstants.TOP);
        quadroAnotar.setHorizontalAlignment(SwingConstants.LEFT);
        quadroAnotar.setVerticalAlignment(SwingConstants.TOP);

        voltarButton.setVisible(false);
        originalButton.setVisible(false);
        anotarPanel.setVisible(false);
        buscarPanel.setVisible(false);
        segmentarPanel.setVisible(true);

        Toolkit tool = Toolkit.getDefaultToolkit();
        Dimension dim = new Dimension(tool.getScreenSize());
        int height = (int) dim.getHeight();
        int width = (int) dim.getWidth();
        setSize(width * 2 / 3, height * 3 / 4);

        segmentaButton.setEnabled(false);
        segmentaButton.setForeground(Color.LIGHT_GRAY);
        mapaRotulosButton.setEnabled(false);
        mapaRotulosButton.setForeground(Color.LIGHT_GRAY);
        anotarButton.setEnabled(false);
        anotarButton.setForeground(Color.LIGHT_GRAY);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        BGPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        buscarMenuButton = new javax.swing.JButton();
        segmentarMenuButton = new javax.swing.JButton();
        anotarMenuButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        segmentarPanel = new javax.swing.JPanel();
        adicionarButton = new javax.swing.JButton();
        mapaRotulosButton = new javax.swing.JButton();
        segmentaButton = new javax.swing.JButton();
        colorRadiusSpinner = new javax.swing.JSpinner();
        minSizeSpinner = new javax.swing.JSpinner();
        blurLevelSpinner = new javax.swing.JSpinner();
        imagePanelSegmentar = new javax.swing.JPanel();
        quadroSegmentar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        regioes = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        anotarPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTextPane();
        anotacao = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        imagePanelAnotar = new javax.swing.JPanel();
        quadroAnotar = new javax.swing.JLabel();
        anotarButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        buscarPanel = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        buscador = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        listPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaNomes = new javax.swing.JList();
        imagePanelBusca = new javax.swing.JPanel();
        quadroBusca = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        voltarButton = new javax.swing.JButton();
        originalButton = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel4.setText("jLabel4");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BGPanel.setBackground(new java.awt.Color(255, 255, 204));

        menuPanel.setBackground(new java.awt.Color(255, 204, 102));

        buscarMenuButton.setBackground(new java.awt.Color(233, 189, 101));
        buscarMenuButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        buscarMenuButton.setForeground(new java.awt.Color(51, 51, 51));
        buscarMenuButton.setText("BUSCAR");
        buscarMenuButton.setBorderPainted(false);
        buscarMenuButton.setContentAreaFilled(false);
        buscarMenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarMenuButtonMouseClicked(evt);
            }
        });

        segmentarMenuButton.setBackground(new java.awt.Color(233, 189, 101));
        segmentarMenuButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        segmentarMenuButton.setForeground(new java.awt.Color(51, 51, 51));
        segmentarMenuButton.setText("SEGMENTAR");
        segmentarMenuButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        segmentarMenuButton.setBorderPainted(false);
        segmentarMenuButton.setContentAreaFilled(false);
        segmentarMenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                segmentarMenuButtonMouseClicked(evt);
            }
        });

        anotarMenuButton.setBackground(new java.awt.Color(233, 189, 101));
        anotarMenuButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        anotarMenuButton.setForeground(new java.awt.Color(51, 51, 51));
        anotarMenuButton.setText("ANOTAR");
        anotarMenuButton.setBorderPainted(false);
        anotarMenuButton.setContentAreaFilled(false);
        anotarMenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anotarMenuButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscarMenuButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(anotarMenuButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(segmentarMenuButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(segmentarMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(anotarMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscarMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(255, 255, 204));
        mainPanel.setEnabled(false);

        segmentarPanel.setBackground(new java.awt.Color(255, 255, 204));

        adicionarButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        adicionarButton.setForeground(new java.awt.Color(102, 102, 102));
        adicionarButton.setText("ADICIONAR IMAGEM");
        adicionarButton.setContentAreaFilled(false);
        adicionarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adicionarButtonMouseClicked(evt);
            }
        });

        mapaRotulosButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        mapaRotulosButton.setForeground(new java.awt.Color(102, 102, 102));
        mapaRotulosButton.setText("MAPA DE RÓTULOS");
        mapaRotulosButton.setBorderPainted(false);
        mapaRotulosButton.setContentAreaFilled(false);
        mapaRotulosButton.setEnabled(false);
        mapaRotulosButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapaRotulosButtonMouseClicked(evt);
            }
        });

        segmentaButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        segmentaButton.setForeground(new java.awt.Color(102, 102, 102));
        segmentaButton.setText("SEGMENTAR");
        segmentaButton.setBorderPainted(false);
        segmentaButton.setContentAreaFilled(false);
        segmentaButton.setEnabled(false);
        segmentaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                segmentaButtonMouseClicked(evt);
            }
        });

        colorRadiusSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(50), Integer.valueOf(1), null, Integer.valueOf(1)));

        minSizeSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(500), Integer.valueOf(1), null, Integer.valueOf(1)));

        blurLevelSpinner.setModel(new javax.swing.SpinnerNumberModel(0.5d, 0.01d, 1.0d, 0.01d));

        imagePanelSegmentar.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout imagePanelSegmentarLayout = new javax.swing.GroupLayout(imagePanelSegmentar);
        imagePanelSegmentar.setLayout(imagePanelSegmentarLayout);
        imagePanelSegmentarLayout.setHorizontalGroup(
            imagePanelSegmentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quadroSegmentar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        imagePanelSegmentarLayout.setVerticalGroup(
            imagePanelSegmentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quadroSegmentar, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Color Radius");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("MinSize");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Blur Level");

        jLabel5.setText("Total de Regiões:");

        regioes.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("SEGMENTAÇÃO");

        javax.swing.GroupLayout segmentarPanelLayout = new javax.swing.GroupLayout(segmentarPanel);
        segmentarPanel.setLayout(segmentarPanelLayout);
        segmentarPanelLayout.setHorizontalGroup(
            segmentarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(segmentarPanelLayout.createSequentialGroup()
                .addGroup(segmentarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(segmentarPanelLayout.createSequentialGroup()
                        .addComponent(imagePanelSegmentar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(segmentarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(segmentarPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(segmentarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(segmentaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mapaRotulosButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, segmentarPanelLayout.createSequentialGroup()
                                        .addGroup(segmentarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(segmentarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(minSizeSpinner, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(colorRadiusSpinner, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(blurLevelSpinner, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addGroup(segmentarPanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(regioes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, segmentarPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(segmentarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(segmentarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, segmentarPanelLayout.createSequentialGroup()
                                .addGap(0, 425, Short.MAX_VALUE)
                                .addComponent(adicionarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(segmentarPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2)))))
                .addContainerGap())
        );
        segmentarPanelLayout.setVerticalGroup(
            segmentarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(segmentarPanelLayout.createSequentialGroup()
                .addGroup(segmentarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(segmentarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(segmentarPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(segmentarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(segmentarPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(segmentarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(blurLevelSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(segmentarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(colorRadiusSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(segmentarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(segmentarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regioes, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(segmentaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(mapaRotulosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(segmentarPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(imagePanelSegmentar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(adicionarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        anotarPanel.setBackground(new java.awt.Color(255, 255, 204));
        anotarPanel.setEnabled(false);

        tabela.setEditable(false);
        jScrollPane2.setViewportView(tabela);

        anotacao.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        anotacao.setText("anote aqui!");

        addButton.setBackground(new java.awt.Color(255, 255, 153));
        addButton.setText("+");
        addButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addButton.setBorderPainted(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(255, 255, 153));
        clearButton.setText("LIMPAR NOTAS");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        imagePanelAnotar.setBackground(new java.awt.Color(255, 255, 204));

        quadroAnotar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quadroAnotarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout imagePanelAnotarLayout = new javax.swing.GroupLayout(imagePanelAnotar);
        imagePanelAnotar.setLayout(imagePanelAnotarLayout);
        imagePanelAnotarLayout.setHorizontalGroup(
            imagePanelAnotarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quadroAnotar, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
        );
        imagePanelAnotarLayout.setVerticalGroup(
            imagePanelAnotarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quadroAnotar, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );

        anotarButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        anotarButton.setForeground(new java.awt.Color(102, 102, 102));
        anotarButton.setText("SALVAR NOTAS");
        anotarButton.setBorderPainted(false);
        anotarButton.setContentAreaFilled(false);
        anotarButton.setEnabled(false);
        anotarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anotarButtonMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("ANOTAÇÃO");

        javax.swing.GroupLayout anotarPanelLayout = new javax.swing.GroupLayout(anotarPanel);
        anotarPanel.setLayout(anotarPanelLayout);
        anotarPanelLayout.setHorizontalGroup(
            anotarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anotarPanelLayout.createSequentialGroup()
                .addContainerGap(422, Short.MAX_VALUE)
                .addGroup(anotarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, anotarPanelLayout.createSequentialGroup()
                        .addGroup(anotarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(anotarPanelLayout.createSequentialGroup()
                                .addComponent(anotacao, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(anotarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, anotarPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, anotarPanelLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3)
                .addContainerGap())
            .addGroup(anotarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(anotarPanelLayout.createSequentialGroup()
                    .addComponent(imagePanelAnotar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 260, Short.MAX_VALUE)))
        );
        anotarPanelLayout.setVerticalGroup(
            anotarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anotarPanelLayout.createSequentialGroup()
                .addGroup(anotarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(anotarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(anotarPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(anotarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(anotacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(anotarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(anotarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(anotarPanelLayout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(imagePanelAnotar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(107, Short.MAX_VALUE)))
        );

        buscarPanel.setBackground(new java.awt.Color(255, 255, 204));
        buscarPanel.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("BUSCA");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel9.setText("Palavra a Procurar:");

        buscador.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        buscador.setPreferredSize(new java.awt.Dimension(414, 21));
        buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscadorKeyPressed(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(255, 153, 51));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTabbedPane1.setFocusable(false);
        jTabbedPane1.setRequestFocusEnabled(false);

        listPanel.setBackground(new java.awt.Color(255, 204, 102));

        listaNomes.setBackground(new java.awt.Color(255, 255, 204));
        listaNomes.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        listaNomes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaNomesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaNomes);

        javax.swing.GroupLayout listPanelLayout = new javax.swing.GroupLayout(listPanel);
        listPanel.setLayout(listPanelLayout);
        listPanelLayout.setHorizontalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addContainerGap())
        );
        listPanelLayout.setVerticalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Nomes das Imagens", listPanel);

        imagePanelBusca.setBackground(new java.awt.Color(255, 255, 204));

        quadroBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quadroBuscaMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel11.setText("Clique na imagem para poder anota-la");

        voltarButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        voltarButton.setForeground(new java.awt.Color(102, 102, 102));
        voltarButton.setText("Voltar");
        voltarButton.setBorderPainted(false);
        voltarButton.setContentAreaFilled(false);
        voltarButton.setEnabled(false);
        voltarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarButtonMouseClicked(evt);
            }
        });

        originalButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        originalButton.setForeground(new java.awt.Color(102, 102, 102));
        originalButton.setText("Original");
        originalButton.setBorderPainted(false);
        originalButton.setContentAreaFilled(false);
        originalButton.setEnabled(false);
        originalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                originalButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout imagePanelBuscaLayout = new javax.swing.GroupLayout(imagePanelBusca);
        imagePanelBusca.setLayout(imagePanelBuscaLayout);
        imagePanelBuscaLayout.setHorizontalGroup(
            imagePanelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelBuscaLayout.createSequentialGroup()
                .addGroup(imagePanelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quadroBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imagePanelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voltarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(originalButton, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
        );
        imagePanelBuscaLayout.setVerticalGroup(
            imagePanelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelBuscaLayout.createSequentialGroup()
                .addComponent(quadroBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(imagePanelBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imagePanelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(originalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Imagem Selecionada", imagePanelBusca);

        javax.swing.GroupLayout buscarPanelLayout = new javax.swing.GroupLayout(buscarPanel);
        buscarPanel.setLayout(buscarPanelLayout);
        buscarPanelLayout.setHorizontalGroup(
            buscarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarPanelLayout.createSequentialGroup()
                .addGroup(buscarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buscarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4))
                    .addGroup(buscarPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(buscarPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1)))
                .addContainerGap())
        );
        buscarPanelLayout.setVerticalGroup(
            buscarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarPanelLayout.createSequentialGroup()
                .addGroup(buscarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buscarPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buscarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(buscarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(buscador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(segmentarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(anotarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(buscarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(segmentarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(anotarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(buscarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BGPanelLayout = new javax.swing.GroupLayout(BGPanel);
        BGPanel.setLayout(BGPanelLayout);
        BGPanelLayout.setHorizontalGroup(
            BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGPanelLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BGPanelLayout.setVerticalGroup(
            BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BGPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BGPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarMenuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMenuButtonMouseClicked
        anotarPanel.setVisible(false);
        buscarPanel.setVisible(true);
        segmentarPanel.setVisible(false);
    }//GEN-LAST:event_buscarMenuButtonMouseClicked

    private void segmentarMenuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_segmentarMenuButtonMouseClicked
        anotarPanel.setVisible(false);
        buscarPanel.setVisible(false);
        segmentarPanel.setVisible(true);
    }//GEN-LAST:event_segmentarMenuButtonMouseClicked

    private void anotarMenuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anotarMenuButtonMouseClicked
        anotarPanel.setVisible(true);
        buscarPanel.setVisible(false);
        segmentarPanel.setVisible(false);
    }//GEN-LAST:event_anotarMenuButtonMouseClicked

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        handler.addAnotacao(tabela, anotacao);
    }//GEN-LAST:event_addButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        handler.clear(tabela);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void segmentaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_segmentaButtonMouseClicked
        if (handler.segmentar(blurLevelSpinner, colorRadiusSpinner, minSizeSpinner, quadroSegmentar, quadroAnotar, regioes)) {
            mapaRotulosButton.setEnabled(true);
            mapaRotulosButton.setForeground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_segmentaButtonMouseClicked

    private void mapaRotulosButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapaRotulosButtonMouseClicked
        handler.mapaRotulos(quadroSegmentar);
    }//GEN-LAST:event_mapaRotulosButtonMouseClicked

    private void adicionarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adicionarButtonMouseClicked
        if (handler.addImagem(quadroSegmentar, regioes)) {
            segmentaButton.setEnabled(true);
            segmentaButton.setForeground(Color.DARK_GRAY);
            mapaRotulosButton.setEnabled(false);
            mapaRotulosButton.setForeground(Color.LIGHT_GRAY);
            anotarButton.setEnabled(false);
            anotarButton.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_adicionarButtonMouseClicked

    private void anotarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anotarButtonMouseClicked
        handler.anotar(tabela);
    }//GEN-LAST:event_anotarButtonMouseClicked

    private void quadroAnotarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quadroAnotarMouseClicked
        if (handler.putSegTOHighLight(evt.getX(), evt.getY(), quadroAnotar)) {
            anotarButton.setEnabled(true);
            anotarButton.setForeground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_quadroAnotarMouseClicked

    private void buscadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscadorKeyPressed
        handler.buscaKeyPressed(evt.getKeyCode(), listaNomes);
    }//GEN-LAST:event_buscadorKeyPressed

    private void listaNomesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaNomesMouseClicked
        if (handler.itemListSelected(listaNomes, quadroBusca, jTabbedPane1)) {
            voltarButton.setVisible(false);
            originalButton.setVisible(true);
        }
    }//GEN-LAST:event_listaNomesMouseClicked

    private void quadroBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quadroBuscaMouseClicked
        if (handler.imageSelClicked(blurLevelSpinner, colorRadiusSpinner, minSizeSpinner, quadroAnotar)) {
            anotarPanel.setVisible(true);
            buscarPanel.setVisible(false);
            segmentarPanel.setVisible(false);
        }
    }//GEN-LAST:event_quadroBuscaMouseClicked

    private void voltarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarButtonMouseClicked
        if( handler.imagemSelecionada(quadroBusca)){
            voltarButton.setVisible(false);
            originalButton.setVisible(true);
        }
    }//GEN-LAST:event_voltarButtonMouseClicked

    private void originalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_originalButtonMouseClicked
       if (handler.imagemOriginal(quadroBusca)) {
            voltarButton.setVisible(true);
            originalButton.setVisible(false);
        }
    }//GEN-LAST:event_originalButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoGUI().setVisible(true);
            }
        });
    }

    private ProjetoGUIHandler handler;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BGPanel;
    private javax.swing.JButton addButton;
    private javax.swing.JButton adicionarButton;
    private javax.swing.JTextField anotacao;
    private javax.swing.JButton anotarButton;
    private javax.swing.JButton anotarMenuButton;
    private javax.swing.JPanel anotarPanel;
    private javax.swing.JSpinner blurLevelSpinner;
    private javax.swing.JTextField buscador;
    private javax.swing.JButton buscarMenuButton;
    private javax.swing.JPanel buscarPanel;
    private javax.swing.JButton clearButton;
    private javax.swing.JSpinner colorRadiusSpinner;
    private javax.swing.JPanel imagePanelAnotar;
    private javax.swing.JPanel imagePanelBusca;
    private javax.swing.JPanel imagePanelSegmentar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel listPanel;
    private javax.swing.JList listaNomes;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton mapaRotulosButton;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JSpinner minSizeSpinner;
    private javax.swing.JButton originalButton;
    private javax.swing.JLabel quadroAnotar;
    private javax.swing.JLabel quadroBusca;
    private javax.swing.JLabel quadroSegmentar;
    private javax.swing.JLabel regioes;
    private javax.swing.JButton segmentaButton;
    private javax.swing.JButton segmentarMenuButton;
    private javax.swing.JPanel segmentarPanel;
    private javax.swing.JTextPane tabela;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
